engines:
  duplication:
	enabled: true
	config:
	  languages:
		- python
  fixme:
	enabled: true
  radon:
	enabled: true
  rubocop:
	enabled: true

ratings:
  paths:
  - "**.py"

exclude_paths:
- "**/tests/**"
- "**/test_**.py"
