language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.9.7

before_install:
- export DJANGO_SETTINGS_MODULE=application.settings
- export PYTHONPATH=$HOME/builds/DataIsTheNewBlack/FeedRadar.IO
- export PIP_USE_MIRRORS=true

install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet

before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres

script:
- python manage.py collectstatic --noinput
- python manage.py migrate
- coverage run manage.py test

after_success:
- codeclimate-test-reporter
- commitID="$(git rev-parse HEAD)"
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region eu-west-1
- aws deploy create-deployment --application-name "FeedRadar_App" --github-location repository="DataIsTheNewBlack/FeedRadar.IO",commitId=$commitID --deployment-group-name "FeedRadar_DeployGroup"
