language: python

addons:
  apt:
    update: false
  postgresql: "10"

dist: trusty

cache:
- pip

python:
- '3.5'
- '3.6'

branches:
  only:
    - master
    - dev
    - /\d+\.\d+(\.\d+)?(\S*)?$/

services:
- rabbitmq
- redis-server
- postgresql

before_install:
- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
- export DJANGO_SETTINGS_MODULE=application.settings
- export PYTHONPATH=$HOME/builds/DEKHTIARJonathan/FeedCrunch.IO
- virtualenv venv

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install coveralls codecov codacy-coverage

before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres

script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- python manage.py collectstatic --noinput
- python manage.py makemigrations feedcrunch
- python manage.py migrate
- python manage.py createcachetable
- coverage run manage.py test
#- coverage xml

after_success:
- coveralls
- codecov
- python-codacy-coverage -r coverage.xml

notifications:
  matrix:
  - email: false
  slack:
    secure: CX3x9d562S90xbISGDBGmdrCeu6Bvv/kezMGDa6U2nOAgu6esDVXFwT4GRIPze4tW8zbH7yuDeRPKTIU+p/GpOu4woS+u/c/n9OYVKwRjfqZE2LhHGmu8QkpXzpeZBSZeRWVFmYkIzsgRNcHkVbyMVJoByKGfAVD3x0ENvm3Sr3Ij2WyvRky6ZrgmTXuhil+Fqph9uamq3C1+G8DyTL9OFnz4hZZSktO29SmL9F3G/hvTMlZ9ezan2LngVPaYllfxWhMxuWkjkt7sdnc1iwlq0yxLxoQmokQao+FGMFlUNRT0ASIG0NhBKU/GJl0XR1l2n4zfy4SiBZaU1aDnQvIiFJABW6GUqdbYi4Fzi/nZS7mZTbMZcBTlHFoG7Ebu6StLINTp5bLk+90sa/RAWG4CXwoDZLSpD6hPeun482Zud3wHKyOAB3rwFP2qR2qwGM+ZMh3+49Ca7ngdloNs3DFhY9ISKLqGgUUD2zcS97U8H8qSAbAqlvzqU1oWhv7AIh2sjU7159XfH3yaXyV9mqtyBCtn9/NrYWt9OtSmb1EsMsP/1OjWGgzDGqaeVsjEINnbm/0ERSHFzRfyKqc+fejQpkVvWj0bA/Z1RB9FBfgZQSzkkLHfxwm/tVF6PVg36NxwD/HGIlRzJFlThB8XcK+j4t2J8kwbkskYyZoM6hOGOQ=

env:
  global:

  - RABBITMQ_URL='amqp://guest:guest@localhost:5672/'
  - REDIS_URL='redis://localhost:6379'
  - DATABASE_URL='postgres://postgres:@localhost:5432/travisci'
  - DEBUG='True'
  - EMAIL_DEFAULT_SENDER='local@local.host'
  - TRAVIS='True'
  - ARTIFACT_NAME='Feedcrunch-Application.zip'
  - BLUEMIX_USERNAME='jonathan.dekhtiar@utc.fr'
  - BLUEMIX_API_GATEWAY='https://api.eu-gb.bluemix.net'
  - BLUEMIX_API_ORGANISATION='FeedCrunch'
  - BLUEMIX_API_SPACE='prod'
  - USE_RABBITMQ='False'

  ### == CODECOV_TOKEN === ###
  - secure: "sRuP0d5h9pZRVHMo+8TjOdx80rJEb9GiR26uEM2dZZvm3oh+jfHbiqSecaLa3yo6qgyLwz3doSZx1eu7ZW6RDujEHHSg/SdHkosLzo3qKE1Mr5XPJXLtwjXcvSVYhiMVS5E/IcrOKqEi5p694GsykLwz5jVb6orCh/O8UcHHb2NP99JhKWcxFRjEpPoitNmTcigd1VJjqf7MiMq8+GqEhe4vug9XCnyUgpUM7okOkbem2DPaABwEJfZC9f0HVlJa1X1r1mGAFJuPqJpJ0sOiimZo9k0yfBSGjTCWmr+aga1ASjMJUKBCiEk+yEAaLwu6w0Zr+nYuIhLeLWDxVwJpmUBs0QFM4RX4Q+Pt3hUs9ynCWrXfcR/1hNdQD76705Bs9/4TxBwT7sOMfdVsywcpWtUPtfFTYmQL1sBMnz1GOg4ueZQHL7+GaARaZs+5XuWiaNIP0/xmFE8C+EHm2OqesgwYD/rdJxYG5VMyfyrjsfEJrZLx0TV8e9xbhEx3x9ZeTJrBV24/qDyYT7Ekn2kY+t8nA7V8NSKkleMiT+5D81PyNLJ0+YJjw/Ot+DIT0U6IkuSi5Y0eQMGq+mRfLGGY3YNCSeo1MTxhy5EO3pX4mwVJZt2QwOQwzqoJyGM8foNu6NH1hBjX6IH3B0smpmLoPoY3TCEffZOYjpSoGOqBQsE="

  ### === CODACY_PROJECT_TOKEN === ###
  - secure: "MJ6PAxlkD+Vch1QcAyJB/isYfzqs/fgVYp5dM/Rq2pj/sisl3TtpkdNyiddlFMONH+BkxLxUnBng4PaJewrnWc6ojUlarSolyYPO+nUiy0if3XPNHtcdoUgR97CGWfrm1U+3Rb/gDN3RNDTmWveISB8B2d3j00dUvQEwdYBmK48RsJ1z0a0bjc4E3D2Ns0RiOsp4kWi+CEsMG7r0AVWpdOgusiVnx4bWgiALQJclJS6xkszB63PjIjNyscWr79KE6YFmYxP0aEOtLh/u7FAuWCWM7oFEvXp+b4gOZi+dH1SeuKpNO1Cm+6O6mR0bfnrYlrJUr8m0USh4Uoqz8Qexn8SxRtR1cFQENyDzrTqi97aInmA9ZtiaAXRDy6gByOZ9uP0SYgqdF2+R0xNGQsVF6mo7vBqDynpqMp39Bi1DfceFP2/7qLIgsiBvSEH9fj903RAg4rlra16JiQKw2jwHN/S3I0PBvkV20AlgAyFjBAcIdvVpi1OjRIOXKPKPZPB3tyc940U0z3tHSJoWDlKWv5jq1W6YvmzV+bqVpHCAoKatQlcePhKv0WwQC0sFQnfs4JgYqBrpQunSzof4l62NsOsW/9Ji7NBQnWadFmTtoyC4pXRDYitq6ZURRasQS929V9OpzAFQbH55guB6RYyRuBdfCJlQlepZOy40ZV9A+5w="

  ### === BluemixPassword === ###
  - secure: "J7TLKPrkrvi120IKuJnqRjuY0+DA1YORhZ7i/3zlEjjEALXaHZ7y2/mdu66ZR1QGkKny6/4bHia9YU5XyxNIQv6lpbrpGyIKjQy4LJZK/VYsBZLMNEV6RVleyIliyZm6iFK+Zmp/MfCioGHz6PI5eI+5vKeOhPwadd9THXTgrjwiX6LgeAX7ItNdfhBkm8UPSxWqAWCDRKVU3wX5kVz3iVKHNPSIS8Prpm+U5WaSSHAPSDyX7ybLhhPP2H1nbvAo1Ieb7f0iMBWXrxfLWM0emQxO5GrIJkaUDUiDXvKiMWGkeJO0p4Bsb/mxRgcfc/YgHkE0o6OxhHyyI1CqLyCqnAecqAnpceskiqnYkSD8lOLjI9d2AdpbG2rsIrxHWyd9njA/iV7cj92HXUdciPugymXOPU2GPw1t8FzkQCctGj+FdDHfnoOjhdRViFKeInIeRRbvf85Cgpu0x0YQlP0l2j5tpgzlfpDLSQ2kZ4Db05KVFCSZF0v1+DYBhY5FrOHIeXDCL2gkKJzzGl2KHKP+Mn+JwNWkhXqV4hIAX5epBuIjVDZY49ClY3vIyx/8Yz9Tw0JQ9YFElbnWxtpXpu2F4sPiBfj3lp4+Ps6cGEORBw0F3YBtKdLFFOsrkIuoKejhUFU3b/ggDIPlFEQWmyMspISK1nxEexxt44Qrb7Z/6ZE="

  ### === GITHUB_OAUTH_TOKEN === ###
  - secure: "tNIHOkE/L5xnyIwYYPPo6NfEkofhwgEN/M89Y0yxkpVj1gna+RKGuIj5qz8wcGyZul1lqp/jiR690W4jd7gAbTyt522pn9KMDckfaLYdMm2O/LvdoCou3t7AuMMwInVxxN75Q+hexu3XeNUCuG3+y5aqtOqj5WiFx59nQpaBW/ljzOCj+JbE30iSXpLdej9K97r/DfxVXjuCLoRJNobQeiJYIQpG934JwOC2bxZViQDr2wXb5Xe16uCpF013P1oPFHTlm2SbrLRidz96jQFWbOj/ktaBEJV1yeFaqdTbEOJd6Jb83NyNrg/pM1ArTpgCw4PYbI7p4ZjlMd9yjYa8zPok9jYuUJj5dHF2l3Ys/M62HkyYdYRRx9v1iZQ5E2x7Xg7eIMWeTguFPqUX24NX/kskAFAfDtU/P994c7MzhoK635Fvmz9R9nr1fRIvZndWwx18XWAYEZp2RW9TEJwbKrwzarmooc8ttDDfjR4aiGJ/yWN2hudUXwUfhD4y0F0VA7jpNmSYm7SrVRV7U8b6+UfcEGNldXlA5lGNIkyOT55O0NGBye87/pHdPV17ESZiR6d6kn20JDlfjnzFctQkFWTN6bAzXq0SptQT2I8YqV1eawFvnjJlbxWfVB5/zjz19cwrqIy8NhQSYtpwiVCf2q95sEpBYaGwbYRMxjbJVMc="

before_deploy:
- find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
- rm -rf venv/
- rm -rf application/staticfiles/
- rm -rf htmlcov/
- if [ -n "$TRAVIS_TAG" ]; then
      zip -r "$ARTIFACT_NAME" . -x   _unused_/\* certificate/\* example_files/\* scripts/\* .git/\*;
  fi

deploy:

- provider: cloudfoundry
  api: "$BLUEMIX_API_GATEWAY"
  username: "$BLUEMIX_USERNAME"
  password: "$BluemixPassword"
  organization: "$BLUEMIX_API_ORGANISATION"
  space: "$BLUEMIX_API_SPACE"
  manifest: manifest.yml
  region: eu-gb
  on:
    branch: master
    python: '3.6'
    repo: DEKHTIARJonathan/FeedCrunch.IO

- provider: cloudfoundry
  api: https://api.eu-gb.bluemix.net
  username: jonathan.dekhtiar@utc.fr
  password: "$BluemixPassword"
  organization: FeedCrunch
  space: prod
  manifest: manifest-dev.yml
  region: eu-gb
  on:
    branch: dev
    python: '3.6'
    repo: DEKHTIARJonathan/FeedCrunch.IO

- provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$ARTIFACT_NAME"
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
    repo: DEKHTIARJonathan/FeedCrunch.IO
