language: python

dist: trusty

cache:
- pip

python:
- '3.4'
- '3.5'
- '3.6'

services:
- rabbitmq
- postgresql

before_install:
- export DJANGO_SETTINGS_MODULE=application.settings
- export PYTHONPATH=$HOME/builds/DEKHTIARJonathan/FeedCrunch.IO
- virtualenv venv

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install coveralls codecov

before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres

script:
- python manage.py collectstatic --noinput
- python manage.py makemigrations feedcrunch
- python manage.py migrate
- python manage.py createcachetable
- coverage run manage.py test

after_success:
- coveralls
- codecov --token=8b655609-dc18-4e1b-ade7-9484c83357df

notifications:
  slack:
    rooms:
      secure: lyTZ6DK0gCPEi4/GUm16SLGvi55QIj84UMPY4+O0Dlu8mxNEabAUeYCVi31Qit13Hlicn+2rt2Nq+OHO5ZJ7jin4geEYen+PgOmHiLtfEs0JLRrjeiJ5MFrn4maBslMCjBNWqSh4ICAXYt/O/w0O/QrtMiogVgbK6Bn6kGCgRBq6qBWSjCbzr92lW5aK8ox3frXnditZzYl9KtffjJHgc9AyaIm441Ysb6V4EkAMQ5Yo+1bgzsSKZ+9lUMeYlhK7oCcqWJNI3iwxHgflhcCEw0C4TcLy7NW71lICvhH3uOExAKIi23OKp+RFh3TN8X0NUqlMpPD0+YSGQw6IiAAtkYEDN+c5mGDB+Erg9hMNVkrIdixOxtgQwDyBkq/RmUmg3s/lWN2fR2TgUwiOZRleGEioiznXCRPoAB9RBl8boMyR8q187zB9FjO4SI3NY+opvuo4Mxxdrc1Q4ARqcSUoC2K280N11L7bZLqO/20EEiRF17HQk7wQBGNrcgjFamhZ8QHdYNTpH2CY1iRgNxPFQCMXsSm2Ap5sAyEu1IA55a750lbA7d9AooDKbtxRp2Q8RCjKitAmSTbDY2oKUebPH97U3HjOsqHxx2/XRB4g9J8diiehbzzs/a44DrnXZwRXsrSAcq72RrLbQ4jQoUtcKO0lfozcddWUXrpvde/J1NU=

env:
  global:

  - RABBITMQ_URL='amqp://guest:guest@localhost:5672/'
  - DATABASE_URL='postgres://postgres:@localhost:5432/travisci'
  - DEBUG='True'
  - EMAIL_DEFAULT_SENDER='local@local.host'
  - TRAVIS='True'
  - ARTIFACT_NAME='Feedcrunch-Application.zip'
  - BLUEMIX_USERNAME='jonathan.dekhtiar@utc.fr'
  - BLUEMIX_API_GATEWAY='https://api.eu-gb.bluemix.net'
  - BLUEMIX_API_ORGANISATION='FeedCrunch'
  - BLUEMIX_API_SPACE='prod'

  ### === BluemixPassword === ###
  - secure: "pCcGxYi4rP0giVfguOMDrH6nq++v5xx0geb1pBQT6C6awF6NoFWfkrZXQSGqx5/G2bP5F4G+djTP0c441bzSSPrUT+oqW47vdrg6vqYRVin/YZFQRlutoHPcckjyyWep2aa5qAbp31yWXCol3MwQPupQl90yQeXKUk4GI9HP3+h9wEKeus0x+RZvLuKVINWNlRWMaIHtnR1J8xTrzCCFqQR4L6Kknv80sxOfTMFyaEKv8dUdAHzrV87J+tYQAaJoKAsMLqdagX88TBK9uRxXmfAX33RCUIdgDlG6zorRFcWG+xEvDcBaygxayZ3lc0niqJfAxJqFwzW5ORjYowzXqlfrswpp49djcTUe+fJePLUeApR92BAVXlr12xrbhYBG9BCaOlPvE5JCtmS2BZpGtuZa3XQ1PD9+R0mu9wFz3YgvFMS1WsFhqpauSp4sTmChvpV64jhkbZtjhIymEdOOxN7r9QNetr8P2JyMT5k86TYl0p7+P1O62ru8tqycujIMVLd5KeyH08K71aNmAjdn46Ft5g3sX+rZm7L19EsFRkojTSh7QY6hXW3YuCX3pVQTR25ZqkyZKFV6aFCP0kio7MdN5VcK9iIvDA15pV/ElFNEVMiGKwkC2MFzGD+Qb6MGqE7I4ShwjdU0qLoey3+KJX5pnGYX+CA6Jz2ac5vW6YM="

  ### === GITHUB_OAUTH_TOKEN === ###
  - secure: "tNIHOkE/L5xnyIwYYPPo6NfEkofhwgEN/M89Y0yxkpVj1gna+RKGuIj5qz8wcGyZul1lqp/jiR690W4jd7gAbTyt522pn9KMDckfaLYdMm2O/LvdoCou3t7AuMMwInVxxN75Q+hexu3XeNUCuG3+y5aqtOqj5WiFx59nQpaBW/ljzOCj+JbE30iSXpLdej9K97r/DfxVXjuCLoRJNobQeiJYIQpG934JwOC2bxZViQDr2wXb5Xe16uCpF013P1oPFHTlm2SbrLRidz96jQFWbOj/ktaBEJV1yeFaqdTbEOJd6Jb83NyNrg/pM1ArTpgCw4PYbI7p4ZjlMd9yjYa8zPok9jYuUJj5dHF2l3Ys/M62HkyYdYRRx9v1iZQ5E2x7Xg7eIMWeTguFPqUX24NX/kskAFAfDtU/P994c7MzhoK635Fvmz9R9nr1fRIvZndWwx18XWAYEZp2RW9TEJwbKrwzarmooc8ttDDfjR4aiGJ/yWN2hudUXwUfhD4y0F0VA7jpNmSYm7SrVRV7U8b6+UfcEGNldXlA5lGNIkyOT55O0NGBye87/pHdPV17ESZiR6d6kn20JDlfjnzFctQkFWTN6bAzXq0SptQT2I8YqV1eawFvnjJlbxWfVB5/zjz19cwrqIy8NhQSYtpwiVCf2q95sEpBYaGwbYRMxjbJVMc="

before_deploy:
- find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
- zip -r "$ARTIFACT_NAME" . -x \*.crypto application/staticfiles/\* venv/\* _unused_/\* venv/\* certificate/\* codedeploy/\* example_files/\* htmlcov/\* scripts/\* lib_bin/\* .git/\*

deploy:

- provider: cloudfoundry
  api: "$BLUEMIX_API_GATEWAY"
  username: "$BLUEMIX_USERNAME"
  password: "$BluemixPassword"
  organization: "$BLUEMIX_API_ORGANISATION"
  space: "$BLUEMIX_API_SPACE"
  manifest: manifest.yml
  region: eu-gb
  on:
    branch: master
    python: '3.6'
    repo: DEKHTIARJonathan/FeedCrunch.IO

- provider: cloudfoundry
  api: https://api.eu-gb.bluemix.net
  username: jonathan.dekhtiar@utc.fr
  password: "$BluemixPassword"
  organization: FeedCrunch
  space: prod
  manifest: manifest-dev.yml
  region: eu-gb
  on:
    branch: dev
    python: '3.6'
    repo: DEKHTIARJonathan/FeedCrunch.IO

- provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$ARTIFACT_NAME"
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
    repo: DEKHTIARJonathan/FeedCrunch.IO
