#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.9.7

before_install:
  - export DJANGO_SETTINGS_MODULE=dataradar_app.settings
  - export PYTHONPATH=$HOME/builds/DEKHTIARJonathan/RSS-Manager
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
