language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
script: python manage.py test
