# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('feedcrunch', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='feeduser',
			name='profile_picture',
			field=models.ImageField(default='', upload_to='D:\\Git Projects\\FeedCrunch.IO\\images/user_photos'),
		),
	]
