# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='social_google_scholar',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
    ]
