# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('feedcrunch', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='feeduser',
			name='twitter_consummer_key',
		),
		migrations.RemoveField(
			model_name='feeduser',
			name='twitter_consummer_secret',
		),
	]
