# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0002_feeduser_social_google_scholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='social_coursera',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_docker',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_kaggle',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_orcid',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
    ]
