# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import feedcrunch.model_files.models_interest
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0002_rss_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, default='images/interest_photos/dummy_stock.jpg', null=True, upload_to=feedcrunch.model_files.models_interest.get_photo_path)),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('rssfeeds', models.ManyToManyField(blank=True, related_name='rel_interests', to='feedcrunch.RSSFeed')),
            ],
        ),
    ]
