# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0002_rssfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=2000)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('guid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('media', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pub_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('rssfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_rss_feed_articles', to='feedcrunch.RSSFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_rss_user_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
