# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('feedcrunch', '0002_auto_20160702_0115'),
		('feedcrunch', '0003_options'),
	]

	operations = [
	]
