# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0003_rssarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='bad_attempts',
            field=models.SmallIntegerField(default=0),
        ),
    ]
