# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import feedcrunch.model_files.models_user


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0003_auto_20160928_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/user_photos/dummy_user.png', null=True, upload_to=feedcrunch.model_files.models_user.get_photo_path),
        ),
    ]
