# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0004_auto_20161016_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
