# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0004_FeedUser_Onboarding_and_Interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeduser',
            name='apikey',
        ),
    ]
