# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0004_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
