# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0005_auto_20160704_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeduser',
            old_name='sex',
            new_name='gender',
        ),
    ]
