# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0006_auto_20160708_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='social_dribbble',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_facebook',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_flickr',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_gplus',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_instagram',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_linkedin',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_pinterest',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_stumble',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_twitter',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_vimeo',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_youtube',
            field=models.URLField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='C:\\Users\\marco\\Desktop\\Git Projects\\FeedCrunch.IO\\images/user_photos'),
        ),
    ]
