# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0006_feeduser_recommendation_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
