# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0007_auto_20160709_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='social_researchgate',
            field=models.URLField(default='', max_length=60),
        ),
    ]
