# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0007_feeduser_apikey_runpython'),
    ]

    operations = [
		migrations.AlterField(
            model_name='feeduser',
            name='apikey',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, null=False),
        ),
    ]
