# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0008_feeduser_apikey_set_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, primary_key=True, serialize=False, validators=[validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
