# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0008_auto_20161116_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssarticle',
            name='recommendation_score',
            field=models.FloatField(default=0),
        ),
    ]
