# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0008_feeduser_social_researchgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='C:\\Users\\marco\\Desktop\\Git Projects\\FeedCrunch.IO\\images/user_photos'),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='rss_feed_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_dribbble',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_facebook',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_flickr',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_gplus',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_instagram',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_linkedin',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_pinterest',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_researchgate',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_stumble',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_twitter',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_vimeo',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='social_youtube',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='twitter_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='twitter_token_secret',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
