# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0009_auto_20160709_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='social_blog',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='social_personalwebsite',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
    ]
