# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0010_feeduser_social_mendeley'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSSubscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField()),
                ('date', models.DateField(auto_now_add=True)),
                ('feedtype', models.CharField(choices=[('rss', 'rss'), ('atom', 'atom')], default='rss', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_rss_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSSSubsStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_rss_subscribers_count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='RSSSubsStat',
            unique_together=set([('user', 'date')]),
        ),
    ]
