# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0010_feeduser_social_mendeley'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSSubscriber',
            fields=[
                ('ipaddress', models.CharField(max_length=250)),
                ('when', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_rss_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
