# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0011_rss_subscribtions_and_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsssubscriber',
            name='feedtype',
            field=models.CharField(choices=[('rss', 'rss'), ('atom', 'atom'), ('web', 'web')], default='rss', max_length=4),
        ),
    ]
