# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0012_rss_subscriber_webType_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsssubscriber',
            name='visit_hour',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
