# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0012_feeduser_rss_subscribers_count_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsssubscriber',
            name='feedtype',
            field=models.CharField(choices=[('rss', 'rss'), ('atom', 'atom')], default='rss', max_length=4),
        ),
    ]
