# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0012_auto_20160710_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeduser',
            name='company_name',
            field=models.CharField(blank=True, default='Holy Paradise Inc.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='feeduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/user_photos/dummy_user.png', null=True, upload_to='images/user_photos'),
        ),
    ]
