# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0013_rsssubscriber_visit_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsssubsstat',
            name='date',
            field=models.DateField(),
        ),
    ]
