# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0014_rsssubsstat_field_date_autonow_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='facebook_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='facebook_token_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='gplus_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='gplus_token_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='linkedin_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='linkedin_token_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='pref_post_autoformat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='pref_post_public_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='pref_post_repost_FB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='pref_post_repost_GPlus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='pref_post_repost_LKin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='pref_post_repost_TW',
            field=models.BooleanField(default=False),
        ),
    ]
