# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0014_auto_20160710_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeduser',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
