# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0014_auto_20160710_0315'),
    ]

    operations = [
        
    ]
