# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0015_user_preferences_and_social_tokens_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='social_stackoverflow',
            field=models.URLField(blank=True, default='', max_length=60, null=True),
        ),
    ]
