# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0020_gplus_replaced_by_slack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('channels', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_slack_integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slackintegration',
            unique_together=set([('team_name', 'user')]),
        ),
    ]
