# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0021_slack_integration_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='error',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
