# Generated by Django 2.1 on 2018-08-04 13:02

from django.db import migrations, models
import functions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0023_FeedUser_default_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeduser',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A user with that username already exists.'}, 
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, 
                primary_key=True, 
                serialize=False, 
                validators=[functions.validators.UnicodeUsernameValidator()], 
                verbose_name='username'
            ),
        ),
    ]
