# Generated by Django 2.1 on 2018-08-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedcrunch', '0024_FeedUser_validator_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeduser',
            old_name='pref_newsletter_subscribtion',
            new_name='pref_newsletter_subscription',
        ),
        migrations.RenameField(
            model_name='rssarticle_assoc',
            old_name='subscribtion',
            new_name='subscription',
        ),
    ]
